### ISSUE TITLE
msgData vs msgPayload

### ISSUE THREAD

**Issue by ethers** [ConsenSys/EthOn#16]
https://github.com/ConsenSys/EthOn/raw/master/doc_resources/img/transaction_concept.png has both msgData and msgPayload.  But are both needed?  If they can be combined, msgData might be the preferred term that's currently more in use (eg `msg.data` in Solidity)

**Comment by jo-tud** [comment]
This might be due to a limitation in the illustration.
Actually, `msgData` and `msgInit` are subtypes of the property `msgPayload`. So any `msgData` and `msgInit` always also is a `msgPayload`. 

This modeling aspect is better visible in the specification. The `msgInit` always also is a `msgPayload` are shown as sublcasses. See https://consensys.github.io/EthOn/EthOn_spec.html#prop-msgpayload

I'm in contact with the creators of VOWL in order to find out if there is a good visual representation for property hierarchies.
@ethers can this be closed or do you have further doubts regarding that? I

**Comment by ethers** [comment]
> Actually, msgData and msgInit are subtypes of the property msgPayload. So msgData and msgInit always also are a msgPayload

I see that EthOn has created `msgInit` and `msgPayload` and that makes sense.  It is a little similar to how EthOn has `ExternalAccount` and `ContractAccount` and as an ontology it makes sense to name both.

But I wonder if it's also important to try highlighting that there's only an Account (the YP doesn't seem to mention anything about ExternalAccount) and that an ExternalAccount is simply an Account that has no code.
Similarly in a transaction there's only 1 "data" field, msgData, and it gets "interpreted" as msgInit if the "to" address is 0, otherwise it is "interpreted" simply as msgData...  That's what you have in https://github.com/ConsenSys/EthOn/raw/master/doc_resources/img/transaction_concept.png  The diagram looks consistent so I'll close.

> I'm in contact with the creators of VOWL in order to find out if there is a good visual representation for property hierarchies.
Sounds good.
